-- MySQL Script generated by MySQL Workbench
-- 02/24/15 22:12:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema seis752justin_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `seis752justin_db` ;

-- -----------------------------------------------------
-- Schema seis752justin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `seis752justin_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `seis752justin_db` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `display_name` VARCHAR(60) NOT NULL,
  `created_when` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `message` VARCHAR(4000) NOT NULL,
  `created_when` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NOT NULL,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `relationship` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_1_id` INT NOT NULL,
  `user_2_id` INT NOT NULL,
  `created_when` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- data.sql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
INSERT INTO `user`
(`id`,
 `username`,
 `password`,
 `display_name`)
VALUES
  (1,'user1','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','AlexanderM'),
  (2,'user2','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','BeccaE'),
  (3,'user3','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','CoryP'),
  (4,'user4','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','DRF'),
  (5,'user5','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','EmilyW'),
  (6,'user6','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','FreddyK'),
  (7,'user7','$1$Yh0.B50.$JaoTIafemHYbEr65N9HhZ0','GeorgeW');

-- -----------------------------------------------------
-- Table `relationship`
-- -----------------------------------------------------
INSERT INTO `relationship`
(`user_1_id`,
 `user_2_id`)
VALUES
  (1,3),
  (3,1),
  (2,4),
  (4,2),
  (2,6),
  (6,2);

